### ISSUE TITLE
大佬你好

### ISSUE THREAD

**Issue by MiaochenLi** [SwordHarry/mit_6.824_2021_lab_chinese_note#1]
我做Lab 4B的时候遇到了一点困难，我和你的方法是一样的，也是用的Push交换分片，但是我几个UnReliable的测试一直无法通过，可以参考下你的代码嘛，谢谢大佬～

**Comment by SwordHarry** [comment]
你好，建议最好是独立完成，你可以将你的问题 或者 bug 放上来我们一起讨论；
实在不行的话留下你的邮箱，我把代码发给你

**Comment by MiaochenLi** [comment]
我有个活锁调了三天还没弄出来😭，有个实现上的细节想和大佬讨论下：
我目前的问题是出现在当一个Group的Leader被孤立时，这时这个group会出现一个多数派的leader和一个少数派的leader，这两个Leader都有权限回复Push RPC，当发送过来的Push RPC Args包含的config.Num等于目前自己的config版本，我就回复OK，然后将收到的Shard Start进raft层；在Push RPC发送方收到OK后就可以删除这个Shard分片的数据了。这里的问题是，如果回复OK的Leader是那个少数派的Leader，它的Start是无效的，因此它回复OK时，会导致Push RPC的发送方误认为自己已经Push成功，可以开始GC了。
为了避免这个问题，我将Push RPC发送方的逻辑改为:  给这个Group的每个成员都发送一遍Push, 这一轮循环完成后，当回复OK的RPC个数大于等于1，就进行一次GC，但是目前活锁的问题依然存在。看到大佬的代码里Push RPC回复的逻辑在startAndApply这个函数里，所以想麻烦大佬能否发送下代码到我的邮箱notmot@163.com，谢谢～

**Comment by MiaochenLi** [comment]
我想了想，问题应该是出在当old Leader被孤立，此时如果新的多数派还处于选举阶段，因此Push RPC仅被发送到了一个少数派Leader，相当于这个Push的日志就丢失了，最后没有被apply，所以需要和Get Put Append一样，设一个chan来跟踪这个push日志是否被apply，apply后才能回复OK～

**Comment by MiaochenLi** [comment]
hello大佬，加上了channel还是不行😭能参考下代码嘛谢谢～

**Comment by SwordHarry** [comment]
> 我目前的问题是出现在当一个Group的Leader被孤立时，这时这个group会出现一个多数派的leader和一个少数派的leader，这两个Leader都有权限回复Push RPC，当发送过来的Push RPC Args包含的config.Num等于目前自己的config版本，我就回复OK，然后将收到的Shard Start进raft层；在Push RPC发送方收到OK后就可以删除这个Shard分片的数据了。这里的问题是，如果回复OK的Leader是那个少数派的Leader，它的Start是无效的，因此它回复OK时，会导致Push RPC的发送方误认为自己已经Push成功，可以开始GC了。

这里有问题，应该是先 start raft，start 成功了才回复 OK，这样可以确保分片成功安装到多数派；我的 lab4B 的日志里也有说明：

> G1 ===== push args ======> G2
G2 Start -> apply
G1 <==== push reply ======= G2
一次 rpc 即可知道 push 成功了，随即 G1 即可进行 GC
G1 Start GC -> apply

**Comment by SwordHarry** [comment]
> 为了避免这个问题，我将Push RPC发送方的逻辑改为: 给这个Group的每个成员都发送一遍Push, 这一轮循环完成后，当回复OK的RPC个数大于等于1，就进行一次GC，但是目前活锁的问题依然存在。看到大佬的代码里Push RPC回复的逻辑在startAndApply这个函数里，所以想麻烦大佬能否发送下代码到我的邮箱notmot@163.com，谢谢～

startAndApply 其实就是一个调用 start，然后用 select case 一个 channel 去接收，一个 time.After 做超时处理，只是单纯想将异步做成同步，当 startAndApply 返回 err 后，证明 start 已经完成或者超时；

**Comment by SwordHarry** [comment]
> 所以想麻烦大佬能否发送下代码到我的邮箱notmot@163.com，谢谢～

同学可以再改改，尽量让自己的实现简单一点，我建议是化繁为简，你这次改完还是不行我再发，你再试试，加油

**Comment by kirkzhangtech** [comment]
大佬，你是不是代码给删了？我记得之前还有了的

**Comment by SwordHarry** [comment]
> 大佬，你是不是代码给删了？我记得之前还有了的

设置了 private，刚开始是 public，但是被提醒了不要公开这样

**Comment by MiaochenLi** [comment]
大佬我把配置更新和shard发送重写了还是不行😭，之前那个old leader问题应该fix了，这次变成经过多次config变化后get获取值的时候差一段字符，辛苦大佬发下代码，我比对下逻辑定位bug，谢谢大佬～

**Comment by SwordHarry** [comment]
> 大佬我把配置更新和shard发送重写了还是不行😭，之前那个old leader问题应该fix了，这次变成经过多次config变化后get获取值的时候差一段字符，辛苦大佬发下代码，我比对下逻辑定位bug，谢谢大佬～

已发，还是建议自己独立完成，加油，如果没有疑问，还请 关闭 issue

**Comment by MiaochenLi** [comment]
感谢大佬，Lab4B终于完成了，在我之前的实现里，我发送分片的RPC每次只发送一个分片，收到reply后将这一个分片GC；然后我将代码改为和大佬一样的每次RPC针对一个Group发送所有本轮对方需要的分片之后就成功了，想问下大佬这个是什么原因呀～

**Comment by SwordHarry** [comment]
我一开始也是使用的逐个分片做push，但在 6824 这个环境里是没有必要的，每个 shard 的数据量其实很小，如果可以一次性以 group 做迁移，在数据量小的情况下是一种优化；
其次，具体还要看 test_test.go 里的实验源码，它其实是有一定的随机性的，比如，测试代码会睡眠2秒之类的，所以我们需要保证在2秒之内完成一轮 config 留下的任务，逐个 shard 迁移可能会超时

**Comment by SwordHarry** [comment]
如果没有疑问，还请关闭 issue

**Comment by kirkzhangtech** [comment]
大佬有没有粉丝群？

**Comment by SwordHarry** [comment]
> 大佬有没有粉丝群？


没有，都是自己自学，还是学生......

**Comment by kirkzhangtech** [comment]
hi harry
哈哈， 你是不是在中山读研究生呀？我前几天看到了你知乎ID, 我是2018年本科毕业。
best regards
kirkzhang


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SwordHarry/mit_6.824_2021_note"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月19日(星期三) 下午2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SwordHarry/mit_6.824_2021_note] 大佬你好 (Issue #1)





  
大佬有没有粉丝群？
  
没有，都是自己自学，还是学生......
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SwordHarry** [comment]
哈哈，学长好，20级研究生，目前还在愁毕业这样


在 2022年1月19日 ***@***.***> 写道：


hi harry 
 哈哈， 你是不是在中山读研究生呀？我前几天看到了你知乎ID, 我是2018年本科毕业。 
 best regards 
 kirkzhang 
 
 
 ------------------&nbsp;原始邮件&nbsp;------------------ 
 发件人: "SwordHarry/mit_6.824_2021_note" ***@***.***&gt;; 
 发送时间:&nbsp;2022年1月19日(星期三) 下午2:17 
 ***@***.***&gt;; 
 ***@***.******@***.***&gt;; 
 主题:&nbsp;Re: [SwordHarry/mit_6.824_2021_note] 大佬你好 (Issue #1) 
 
 
 
 
 
 
 大佬有没有粉丝群？ 
 
 没有，都是自己自学，还是学生...... 
 
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 You are receiving this because you commented.Message ID: ***@***.***&gt;
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kirkzhangtech** [comment]
hi&nbsp;
哈哈，是同学，看你代码有些地方不太懂，想讨论讨论




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SwordHarry/mit_6.824_2021_note"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月19日(星期三) 下午2:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SwordHarry/mit_6.824_2021_note] 大佬你好 (Issue #1)





 哈哈，学长好，20级研究生，目前还在愁毕业这样
 
 
 在 2022年1月19日 ***@***.***&gt; 写道：
 
 
 hi harry 
  哈哈， 你是不是在中山读研究生呀？我前几天看到了你知乎ID, 我是2018年本科毕业。 
  best regards 
  kirkzhang 
  
  
  ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
  发件人: "SwordHarry/mit_6.824_2021_note" ***@***.***&amp;gt;; 
  发送时间:&amp;nbsp;2022年1月19日(星期三) 下午2:17 
  ***@***.***&amp;gt;; 
  ***@***.******@***.***&amp;gt;; 
  主题:&amp;nbsp;Re: [SwordHarry/mit_6.824_2021_note] 大佬你好 (Issue #1) 
  
  
  
  
  
  
  大佬有没有粉丝群？ 
  
  没有，都是自己自学，还是学生...... 
  
  — 
  Reply to this email directly, view it on GitHub, or unsubscribe. 
  Triage notifications on the go with GitHub Mobile for iOS or Android. 
  You are receiving this because you commented.Message ID: ***@***.***&amp;gt;
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 You are receiving this because you commented.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
